name: RevolveStudents
favicon: null
layout_spectrum: 0.98897
typography_spectrum: 0.685980117181316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090303'
    - '#2fe5fa'
    - '#ffffff'
    - '#0c393f'
    - '#808080'
  brandStrength: 0.8462865797337145
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
